### ISSUE TITLE
Messages Are Not Dismissible & Don't Get Dismissed Automatically

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziKt#153]
### Description

Messages are currently not dismissed & uploading measurements does not show the messages being dismissed.

### Reproduction

- [ ] Interact with a message (e.g. the welcome video) and the message is not dismissed.
- [ ] Do a blood pressure measurement & weight scale measurement, the messages are not automatically dismissed

### Expected behavior

Messages should be dismissed.

### Additional context

it seems like it is not longer possible to set the completionDate of the message and one has to use a firebaseFunction instead ([for reference](https://github.com/StanfordBDHG/ENGAGE-HF-Firebase?tab=readme-ov-file#dismissmessage)). the code would need to be changed to something like:
```
firebaseFunctions.getHttpsCallable("dismissMessage")
    .call(
          mapOf(
            "userId" to uid,
            "messageId" to messageId,
            )
        ).await()
```
from previous:
```
firestore.collection("users")
    .document(uid)
    .collection("messages")
    .document(messageId)
    .update("completionDate", ZonedDateTime.now())
```
implementation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@Basler182 might be able to add some more context on the cloud functions.

**Comment by Basler182** [comment]
I tested it yesterday: On my device, the message for Vitals was automatically removed as it does not need to be dismissed manually, but only receive the vitals. However, it takes some time for the backend to process the measurements and propagate them to the Firestore. In my case, the message disappeared about 10 seconds after the measurements were sent.

The “simple” messages, such as the welcome video, were not dismissed. The reason for this is a change in the dismiss mechanism: instead of setting the [completion date manually](https://github.com/StanfordSpezi/SpeziKt/blob/0c864f3a06298fb12a6df57bb846293a0296dccc/app/src/main/kotlin/edu/stanford/bdh/engagehf/messages/MessageRepository.kt#L53 ), a Firebase function must now be called to take over this task. This function also offers a third parameter, `didPerformAction`. @pauljohanneskraft  might have to provide context for this, as I was not involved.

**Comment by PSchmiedmayer** [comment]
Thank you for the context @Basler182! Good to hear that the could function is working as expected; @pauljohanneskraft is working on a fix for the questionnaires to be parsed correctly and they should be released soon.
