### ISSUE TITLE
Tab titles display

### ISSUE THREAD

**Issue by eldcn** [StanfordSpezi/SpeziKt#77]
### Problem

In smaller devices the tab titles are displayed in two rows which causes the tab row to increase its height

### Solution

Consider either dynamic font sizes for the titles, alternative shorter titles or simply displaying an icon instead of text

### Additional context

<img width="315" alt="Screenshot 2024-08-08 at 14 18 21" src="https://github.com/user-attachments/assets/ec0fb194-2156-4c01-85cb-d140d6c725e8">

![Screenshot 2024-08-08 at 14 20 10](https://github.com/user-attachments/assets/d9c98080-1e79-4c1f-8f93-a949fa2c32cc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Basler182** [comment]
@PSchmiedmayer which of the suggestions do you prefer?

**Comment by PSchmiedmayer** [comment]
I'll think about it in more detail but for now I am fine with the two lines if it happens in some edge cases on smaller screens. BP is a generally well used abbreviation for blood pressure which we could use.

I am not a huge fan of showing icons in the top segmented bar. I would rather try to find strings that are shorter. On the other hand it will be challenging so we will have two lines for multiple different locales in the future.

I can see icons only as an option for the bottom bar, especially if it's size increases with two or more lines.

**Comment by Basler182** [comment]
The problem could arise in particular because many of the users are older and have activated larger fonts. To save space in the bottom bar, we could consider reducing "Heart Health" to "Health". As the app focuses exclusively on heart issues, this would be consistent - similar to "Medication", which is also not called "Heart Medication". This could at least partially alleviate the problem. We have to keep in mind, an entry will still be added to both the top (Symptoms) and bottom (Devices) bar. In the first step, I would then shorten Blood Pressure to BP and, if desired, also omit the Heart from Health. Would that be in your favour, @PSchmiedmayer ?

**Comment by PSchmiedmayer** [comment]
Sounds good to me! Fine with just naming it health.

I think the devices tab might move into the account settings in the top bar. We might do the same thing for iOS as well.
